### ISSUE TITLE
Crash with Botania

### ISSUE THREAD

**Issue by DanDragon401** [AzureDoom/AzureDoom-Doom-Mod#11]
The game won't load if both this mod and Botania is installed. It instead crashes. Here's the crash report: https://pastebin.com/zcW6UkPS

**Comment by AzureDoom** [comment]
I don't see how as the issue here is 
`Caused by: java.io.FileNotFoundException: botania:particles/wisp.json`

Here I launched the game just fine with the two mods installed.
![image](https://user-images.githubusercontent.com/7415711/95262899-fcd57c80-07fa-11eb-9027-19417dfc1124.png)


Also update you're forge, you are super super behind on 34.0.9 when 34.1.11 is the latest.

**Comment by DanDragon401** [comment]
When I remove your mod the game doesn't crash. This is my log with the mod: https://pastebin.com/iyJi3w10 Here's my log without it: https://pastebin.com/hXWVpWPW

**Comment by DanDragon401** [comment]
Lol, may be missing a dependency

**Comment by DanDragon401** [comment]
Now that I have Gecko Lib it's working. Sorry for that.

**Comment by AzureDoom** [comment]
Yes you need Geckolib, but the error you first posted was for Botania not mine.

**Comment by DanDragon401** [comment]
Apparently not having Gecko Lib causes that error for some reason. Someone already confirmed that Botania wasn't the issue in their crash reports.

**Comment by AzureDoom** [comment]
Yeah... It's almost like it's marked as depend or something >.> 
![image](https://user-images.githubusercontent.com/7415711/95265005-4ffcfe80-07fe-11eb-8de6-f6db8728d986.png)

**Comment by DanDragon401** [comment]
I forgot to check the dependencies.
